phaimi.lo: /Users/haimi/Projects/phaimi/phaimi/phaimi.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/haimi/Projects/phaimi/phaimi $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/haimi/Projects/phaimi/phaimi/phaimi.c -o phaimi.lo 
$(phplibdir)/phaimi.la: ./phaimi.la
	$(LIBTOOL) --mode=install cp ./phaimi.la $(phplibdir)

./phaimi.la: $(shared_objects_phaimi) $(PHAIMI_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_phaimi) $(PHAIMI_SHARED_LIBADD)

