#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include "php.h"
#include "php_ini.h"
#include <zend_constants.h>
#include "nitro_api.h"
#include "php_nitrophp.h"

static function_entry nitrophp_functions[] = {
    PHP_FE(hello_world, NULL)
    {NULL, NULL, NULL}
};

zend_module_entry nitrophp_module_entry = {
#if ZEND_MODULE_API_NO >= 20010901
    STANDARD_MODULE_HEADER,
#endif
    PHP_NITROPHP_EXTNAME,
    nitrophp_functions,
    PHP_MINIT(nitrophp),
    PHP_MSHUTDOWN(nitrophp),
    NULL,
    NULL,
    NULL,
#if ZEND_MODULE_API_NO >= 20010901
    PHP_NITROPHP_VERSION,
#endif
    STANDARD_MODULE_PROPERTIES
};

PHP_INI_BEGIN()
PHP_INI_ENTRY("nitrophp.greeting", "Hello %s!", PHP_INI_ALL, NULL)
PHP_INI_END()

PHP_MINIT_FUNCTION(nitrophp)
{
	/**
	 * CONSTANTS:
	 */
 
	 /**
	 * Errors:
	 */
	 // NITRO_ERR_NONE                  0
	 REGISTER_LONG_CONSTANT("NITRO_ERR_NONE", 0, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_ERRNO                 1
	 REGISTER_LONG_CONSTANT("NITRO_ERR_ERRNO", 1, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_ALREADY_RUNNING       2
	 REGISTER_LONG_CONSTANT("NITRO_ERR_ALREADY_RUNNING", 2, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_NOT_RUNNING           3
	 REGISTER_LONG_CONSTANT("NITRO_ERR_NOT_RUNNING", 3, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_TCP_LOC_NOCOLON       4
	 REGISTER_LONG_CONSTANT("NITRO_ERR_TCP_LOC_NOCOLON", 4, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_TCP_LOC_BADPORT       5
	 REGISTER_LONG_CONSTANT("NITRO_ERR_TCP_LOC_BADPORT", 5, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_TCP_LOC_BADIPV4       6
	 REGISTER_LONG_CONSTANT("NITRO_ERR_TCP_LOC_BADIPV4", 6, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_PARSE_BAD_TRANSPORT   7
	 REGISTER_LONG_CONSTANT("NITRO_ERR_PARSE_BAD_TRANSPORT", 7, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_EAGAIN                8
	 REGISTER_LONG_CONSTANT("NITRO_ERR_EAGAIN", 8, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_NO_RECIPIENT          9
	 REGISTER_LONG_CONSTANT("NITRO_ERR_NO_RECIPIENT", 9, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_ENCRYPT               10
	 REGISTER_LONG_CONSTANT("NITRO_ERR_ENCRYPT", 10, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_DECRYPT               11
	 REGISTER_LONG_CONSTANT("NITRO_ERR_DECRYPT", 11, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_INVALID_CLEAR         12
	 REGISTER_LONG_CONSTANT("NITRO_ERR_INVALID_CLEAR", 12, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_MAX_FRAME_EXCEEDED    13
	 REGISTER_LONG_CONSTANT("NITRO_ERR_MAX_FRAME_EXCEEDED", 13, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_BAD_PROTOCOL_VERSION  14
	 REGISTER_LONG_CONSTANT("NITRO_ERR_BAD_PROTOCOL_VERSION", 14, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_DOUBLE_HANDSHAKE      15
	 REGISTER_LONG_CONSTANT("NITRO_ERR_DOUBLE_HANDSHAKE", 15, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_NO_HANDSHAKE          16
	 REGISTER_LONG_CONSTANT("NITRO_ERR_NO_HANDSHAKE", 16, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_BAD_SUB               17
	 REGISTER_LONG_CONSTANT("NITRO_ERR_BAD_SUB", 17, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_BAD_HANDSHAKE         18
	 REGISTER_LONG_CONSTANT("NITRO_ERR_BAD_HANDSHAKE", 18, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_INVALID_CERT          19
	 REGISTER_LONG_CONSTANT("NITRO_ERR_INVALID_CERT", 19, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_BAD_INPROC_OPT        20
	 REGISTER_LONG_CONSTANT("NITRO_ERR_BAD_INPROC_OPT", 20, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_BAD_SECURE            21
	 REGISTER_LONG_CONSTANT("NITRO_ERR_BAD_SECURE", 21, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_INPROC_ALREADY_BOUND  22
	 REGISTER_LONG_CONSTANT("NITRO_ERR_INPROC_ALREADY_BOUND", 22, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_INPROC_NOT_BOUND      23
	 REGISTER_LONG_CONSTANT("NITRO_ERR_INPROC_NOT_BOUND", 23, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_INPROC_NO_CONNECTIONS 24
	 REGISTER_LONG_CONSTANT("NITRO_ERR_INPROC_NO_CONNECTIONS", 24, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_SUB_ALREADY           25
	 REGISTER_LONG_CONSTANT("NITRO_ERR_SUB_ALREADY", 25, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_SUB_MISSING           26
	 REGISTER_LONG_CONSTANT("NITRO_ERR_SUB_MISSING", 26, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_TCP_BAD_ANY           27
	 REGISTER_LONG_CONSTANT("NITRO_ERR_TCP_BAD_ANY", 27, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_ERR_GAI                   28
	 REGISTER_LONG_CONSTANT("NITRO_ERR_GAI", 28, CONST_CS | CONST_PERSISTENT); 
 
	 /**
	  * Frame Constants
	  */
	 // NITRO_FRAME_DATA                0
	 REGISTER_LONG_CONSTANT("NITRO_FRAME_DATA", 0, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_FRAME_SUB                 1
	 REGISTER_LONG_CONSTANT("NITRO_FRAME_SUB", 1, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_FRAME_HELLO               2 
	 REGISTER_LONG_CONSTANT("NITRO_FRAME_HELLO", 2, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_FRAME_SECURE              3
	 REGISTER_LONG_CONSTANT("NITRO_FRAME_SECURE", 4, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_MAX_FRAME 			    1024 // 1024 // 1024
	 REGISTER_LONG_CONSTANT("NITRO_MAX_FRAME", 1073741824, CONST_CS | CONST_PERSISTENT); 
 
	 /**
	 * Other Constants:
	 */
	 // NITRO_NOBLOCK
	 REGISTER_LONG_CONSTANT("NITRO_NOBLOCK", 0, CONST_CS | CONST_PERSISTENT); 
	 // NITRO_REUSE 					1
	 REGISTER_LONG_CONSTANT("NITRO_REUSE", 1, CONST_CS | CONST_PERSISTENT); 
	 // NITOR_NOWAIT                   	2
	 REGISTER_LONG_CONSTANT("NITOR_NOWAIT", 2, CONST_CS | CONST_PERSISTENT); 
 
    REGISTER_INI_ENTRIES();

    return SUCCESS;
}

PHP_MSHUTDOWN_FUNCTION(nitrophp)
{
    UNREGISTER_INI_ENTRIES();

    return SUCCESS;
}

#ifdef COMPILE_DL_NITROPHP
ZEND_GET_MODULE(nitrophp)
#endif

PHP_FUNCTION(hello_world)
{
	RETURN_STRING(INI_STR("nitrophp.greeting"), 1);
}